CREATE OR REPLACE TABLE NBA_DB.RAW.RAW_PLAYER_GAME_LOGS (
    GAME_ID             VARCHAR(20)    NOT NULL COMMENT 'Unique game identifier (PK component)',
    PLAYER_ID           INTEGER        NOT NULL COMMENT 'Unique player identifier (PK component)',
    PLAYER_NAME         VARCHAR(100)             COMMENT 'Full player name',
    TEAM_ID             INTEGER                  COMMENT 'Team identifier (FK -> RAW_TEAMS.ID)',
    TEAM_ABBREVIATION   VARCHAR(5)               COMMENT '3-letter team abbreviation e.g. LAL',
    GAME_DATE           VARCHAR(20)              COMMENT 'Game date as string YYYY-MM-DD',
    MATCHUP             VARCHAR(20)              COMMENT 'Matchup string e.g. LAL vs. BOS or LAL @ BOS',
    WL                  VARCHAR(1)               COMMENT 'Win or loss: W or L',
    MIN                 FLOAT                    COMMENT 'Minutes played',
    PTS                 INTEGER                  COMMENT 'Points scored',
    FGM                 INTEGER                  COMMENT 'Field goals made',
    FGA                 INTEGER                  COMMENT 'Field goals attempted',
    FG_PCT              FLOAT                    COMMENT 'Field goal percentage',
    FG3M                INTEGER                  COMMENT '3-point field goals made',
    FG3A                INTEGER                  COMMENT '3-point field goals attempted',
    FG3_PCT             FLOAT                    COMMENT '3-point field goal percentage',
    FTM                 INTEGER                  COMMENT 'Free throws made',
    FTA                 INTEGER                  COMMENT 'Free throws attempted',
    FT_PCT              FLOAT                    COMMENT 'Free throw percentage',
    OREB                INTEGER                  COMMENT 'Offensive rebounds',
    DREB                INTEGER                  COMMENT 'Defensive rebounds',
    REB                 INTEGER                  COMMENT 'Total rebounds',
    AST                 INTEGER                  COMMENT 'Assists',
    STL                 INTEGER                  COMMENT 'Steals',
    BLK                 INTEGER                  COMMENT 'Blocks',
    TOV                 INTEGER                  COMMENT 'Turnovers',
    PF                  INTEGER                  COMMENT 'Personal fouls',
    PLUS_MINUS          FLOAT                    COMMENT 'Plus/minus for the game',
    NBA_FANTASY_PTS     FLOAT                    COMMENT 'NBA official fantasy points for the game',
    CONSTRAINT PK_RAW_PLAYER_GAME_LOGS PRIMARY KEY (GAME_ID, PLAYER_ID)
)
COMMENT = 'Raw player box score data per game, loaded from nba_api PlayerGameLogs. One row per player per game.';